### ISSUE TITLE
VM compile problem

### ISSUE THREAD

**Issue by sugarjintong** [Seeed-Studio/CodeCraft#18]
D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\cli.js:244
                                throw err;
                                ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './src/index.js' is not defined by "exports" in D:\CodeCraft-main\CodeCraft-main\vm\node_modules\scratch-render\package.json
    at exportsNotFound (node:internal/modules/esm/resolve:304:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:651:9)
    at resolveExports (node:internal/modules/cjs/loader:634:36)
    at Module._findPath (node:internal/modules/cjs/loader:724:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1211:27)
    at Function.resolve (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\v8-compile-cache\v8-compile-cache.js:164:23)
    at Object.<anonymous> (D:\CodeCraft-main\CodeCraft-main\vm\webpack.config.js:137:35)
    at Module._compile (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\cli.js:241:39
    at Object.parse (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\node_modules\yargs\yargs.js:567:18)
    at D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\CodeCraft-main\CodeCraft-main\vm\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.18.0

**Comment by baorepo** [comment]
@vongomben  It seems that you have solved this problem, can you provide a solution?
